spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testhybernate
    username: developer
    password: Cris1997
server:
  port: 7070
jpa:
  database: mysql
  show_sql: true
  hibernate:
    ddl-auto: create-drop
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testhybernate
    username: developer
    password: Cris1997
server:
  port: 4000
jpa:
  database: mysql
  show_sql: true
  hibernate:
    ddl-auto: create-drop

